### PR TITLE
Imagetreatment

### PR DESCRIPTION
**Pull request by ferrigno**
I made several patches to have it working.
I introduced the source identification using the ISDC Reference Catalog
I introduced the possibility to insert additional sources.
I used the original name of the eecutable: "sex",
An example of usage is 
https://gitlab.astro.unige.ch/reproducible_INTEGRAL_analyses/igrj17315/-/blob/master/Sextractor.ipynb
However, one needs the input mosaics to run the notebook, which can be asked.

### CODE REVIEW

**Comment by ferrigno** [comment]
It should be finished. HAve you merged it?

**Comment by volodymyrss** [comment]
I did not merge it, as you can see. I think we agreed that instead of making review, I make the necessary adaptations myself, and then merge. I can do it soon, maybe today.

Oh, by the way, did you cite the tool in your paper?

**Comment by ferrigno** [comment]
I cite sextractor and I aknowledge your adaptation, not this tool directly

**Comment by volodymyrss** [comment]
> I cite sextractor and I aknowledge your adaptation, not this tool directly

My adaptation is in this code. Why not refer to it directly?

**Comment by ferrigno** [comment]
I will do it in the revised version, no problem.

**Pull request merged**
